### ISSUE TITLE
add license badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/fastret-framework#9]
Add the below code in README with other badges

```
[![LICENSE](https://img.shields.io/npm/l/fastret-framework.svg)](https://github.com/arshadkazmi42/fastret-framework/LICENSE)
```

**Comment by atjustbeinghumaid** [comment]
I want to contribute 🙋‍♂️
What do I have to do

**Comment by arshadkazmi42** [comment]
You have to add this line
`[![LICENSE](https://img.shields.io/npm/l/fastret-framework.svg)](https://github.com/arshadkazmi42/fastret-framework/LICENSE)`

above this line
`Fastest rest api test suite builder`

in this file [README.md](https://github.com/arshadkazmi42/fastret-framework/blob/master/README.md)
